---
- name: this is to setup tomcat
  hosts: all
  become: yes

  tasks:
  - name: this is to install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Debian
    apt:
       name: default-jdk
       state: present
    when: ansible_os_family == "Debian"

  - name: installing tomcat
    get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz
        dest: /opt

  - name: to extract the zip file
    unarchive:
         src: /opt/apache-tomcat-8.5.72.tar.gz
         dest: /opt
         remote_src: yes

  - name: changing permissions
    file:
       path: /opt/apache-tomcat-8.5.72/bin/startup.sh
       mode: 0777

  - name: starting tomcat
    shell: ./startup.sh
    args:
       chdir: /opt/apache-tomcat-8.5.72/bin
      
